version: '3.8'

services:
  projeqtor:
    build:
      context: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - projeqtor_data:/opt/projeqtor

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: projeqtor
      POSTGRES_USER: projeqtor
      POSTGRES_PASSWORD: projeqtor
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  projeqtor_data:
