version: '3.8'

services:
  projeqtor:
    build:
      context: .
    environment:
      DB_TYPE: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: projeqtor
      DB_PASSWORD: projeqtor
      DB_NAME: projeqtor
      DB_DISPLAY_NAME: ProjeQtOr
      DB_PREFIX: ''
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - projeqtor_data:/opt/projeqtor

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: projeqtor
      POSTGRES_USER: projeqtor
      POSTGRES_PASSWORD: projeqtor
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  projeqtor_data:
